# Build on all three platforms
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      buildosname: 'linux'
      outputArchiveType: 'tar'
      outputArchiveExtension: 'tar.gz'
    mac:
      imageName: 'macos-10.14'
      buildosname: 'macos'
      outputArchiveType: 'tar'
      outputArchiveExtension: 'tar.gz'
    windows:
      imageName: 'vs2017-win2016'
      buildosname: 'windows'
      outputArchiveType: 'zip'
      outputArchiveExtension: 'zip'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath' # Options: filePath, inline
    scriptPath: create_build_environment.py
    #arguments: # Optional
  displayName: 'Create miniconda build environment'

# Upload artifactory build info
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'devops-ccdc-3rd-party'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "$(Build.ArtifactStagingDirectory)/conda_buildenv*",
            "target": "ccdc-3rdparty-python-interpreters"
          }
        ]
      }
    replaceSpecVars: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)-$(buildosname)'
    module: 'conda_buildenv/$(buildosname)'
    includeEnvVars: true
    failNoOp: true
  displayName: 'Upload distribution to artifactory'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'devops-ccdc-3rd-party'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)-$(buildosname)'
    excludeEnvVars: '*password*;*secret*;*key*;*token*'
  displayName: 'Publish build'
